export const FLAGS: { [key: string]: string } = {
  default: '🇪🇺',
  arg: '🇦🇷',
  bra: '🇧🇷',
  can: '🇨🇦',
  chl: '🇨🇱',
  chn: '🇨🇳',
  fra: '🇫🇷',
  ger: '🇩🇪',
  irn: '🇮🇷',
  jap: '🇯🇵',
  kor: '🇰🇷',
  nld: '🇳🇱',
  pol: '🇵🇱',
  rus: '🇷🇺',
  sgp: '🇸🇬',
  tur: '🇹🇷',
  uae: '🇦🇪',
  usa: '🇺🇸',
  zaf: '🇿🇦',
};

export const SERVERS: { [key: string]: string } = {
  novice: 'Novice - 简单',
  moderate: 'Moderate - 中阶',
  brutal: 'Brutal - 高阶',
  insane: 'Insane - 疯狂',
  dummy: 'Dummy - 分身',
  ddmax: 'DDmaX - 古典',
  oldschool: 'Oldschool - 传统',
  solo: 'Solo - 单人',
  race: 'Race - 竞速',
  fun: 'Fun - 娱乐',
};

export const SERVERS_SHORT: { [key: string]: string } = {
  novice: '简单',
  moderate: '中阶',
  brutal: '高阶',
  insane: '疯狂',
  dummy: '分身',
  ddmax: '古典',
  oldschool: '传统',
  solo: '单人',
  race: '竞速',
  fun: '娱乐',
};
