export const FLAGS: { [key: string]: string } = {
  default: '🇪🇺',
  arg: '🇦🇷',
  bra: '🇧🇷',
  can: '🇨🇦',
  chl: '🇨🇱',
  chn: '🇨🇳',
  fra: '🇫🇷',
  ger: '🇩🇪',
  irn: '🇮🇷',
  jap: '🇯🇵',
  kor: '🇰🇷',
  nld: '🇳🇱',
  pol: '🇵🇱',
  rus: '🇷🇺',
  sgp: '🇸🇬',
  tur: '🇹🇷',
  uae: '🇦🇪',
  usa: '🇺🇸',
  zaf: '🇿🇦',
};

export const SERVERS: { [key: string]: string } = {
  novice: 'Novice - 简单',
  moderate: 'Moderate - 中阶',
  brutal: 'Brutal - 高阶',
  insane: 'Insane - 疯狂',
  dummy: 'Dummy - 分身',
  ddmax: 'DDmaX - 古典',
  oldschool: 'Oldschool - 传统',
  solo: 'Solo - 单人',
  race: 'Race - 竞速',
  fun: 'Fun - 娱乐',
};

export const SERVERS_SHORT: { [key: string]: string } = {
  novice: '简单',
  moderate: '中阶',
  brutal: '高阶',
  insane: '疯狂',
  dummy: '分身',
  ddmax: '古典',
  oldschool: '传统',
  solo: '单人',
  race: '竞速',
  fun: '娱乐',
};

export const QMOTE: {
  [key: number]: { name: string; emoji?: string; eng?: string; removed?: boolean };
} = {
  0: { name: '惊讶', eng: 'surprised', emoji: '😲' },
  1: { name: '撇嘴', eng: 'no idea', emoji: '😟' },
  2: { name: '色', eng: 'heart eyes', emoji: '😍' },
  3: { name: '发呆', eng: 'dazing', emoji: '😳' },
  4: { name: '得意', eng: 'complacent', emoji: '😎' },
  5: { name: '流泪', eng: 'crying', emoji: '😭' },
  6: { name: '害羞', eng: 'shy', emoji: '😊' },
  7: { name: '闭嘴', eng: 'shut up', emoji: '🤐' },
  8: { name: '睡', eng: 'zzz', emoji: '😪' },
  9: { name: '大哭', eng: 'tear up', emoji: '😢' },
  10: { name: '尴尬', eng: 'awkward' },
  11: { name: '发怒', eng: 'angry', emoji: '😡' },
  12: { name: '调皮', eng: 'cheeky', emoji: '😛' },
  13: { name: '呲牙', eng: 'grinning', emoji: '😁' },
  14: { name: '微笑', eng: 'smile', emoji: '🙂' },
  15: { name: '难过', eng: 'sad', emoji: '🙁' },
  16: { name: '酷', eng: 'deal with it' },

  18: { name: '抓狂', eng: 'frustrated', emoji: '😫' },
  19: { name: '吐', eng: 'vomiting', emoji: '🤮' },
  20: { name: '偷笑', eng: 'stealth chuckle', emoji: '🤭' },
  21: { name: '可爱', eng: 'cute', emoji: '😊' },
  22: { name: '白眼', eng: 'rolling eyes', emoji: '🙄' },
  23: { name: '傲慢', eng: 'arrogant', emoji: '😕' },
  24: { name: '饥饿', eng: 'hungry', emoji: '😋' },
  25: { name: '困', eng: 'sleepy', emoji: '😪' },
  26: { name: '惊恐', eng: 'frightened', emoji: '😨' },
  27: { name: '流汗', eng: 'sweat', emoji: '😓' },
  28: { name: '憨笑', eng: 'honest smile', emoji: '😀' },
  29: { name: '悠闲', eng: 'slacking' },
  30: { name: '奋斗', eng: 'strive' },
  31: { name: '咒骂', eng: 'cursing', emoji: '🤬' },
  32: { name: '疑问', eng: 'uncertain' },
  33: { name: '嘘', eng: 'shhh', emoji: '🤫' },
  34: { name: '晕', eng: 'dizzy', emoji: '😵' },
  35: { name: '折磨', eng: 'mentally tormented', emoji: '😣' },
  36: { name: '衰', eng: 'bombed', emoji: '😢' },
  37: { name: '骷髅', eng: 'skull', emoji: '💀' },
  38: { name: '敲打', eng: 'bonk', emoji: '🤕' },
  39: { name: '再见', eng: 'bye', emoji: '👋' },

  41: { name: '发抖', eng: 'shaking', emoji: '🥶' },
  42: { name: '爱情', eng: 'couple in love', emoji: '💑' },
  43: { name: '跳跳', eng: 'jumpy jump' },

  46: { name: '猪头', eng: 'pig', emoji: '🐷' },

  49: { name: '拥抱', eng: 'hug', emoji: '🤗' },

  53: { name: '蛋糕', eng: 'cake', emoji: '🎂' },
  54: { name: '闪电', eng: 'lightning bolt', emoji: '⚡' },
  55: { name: '炸弹', eng: 'bomb', emoji: '💣' },
  56: { name: '刀', eng: 'knife', emoji: '⚔' },
  57: { name: '足球', eng: 'soccer', emoji: '⚽' },

  59: { name: '便便', eng: 'poop', emoji: '💩' },
  60: { name: '咖啡', eng: 'coffee', emoji: '☕' },
  61: { name: '饭', eng: 'rice', emoji: '🍚' },

  63: { name: '玫瑰', eng: 'rose', emoji: '🌹' },
  64: { name: '凋谢', eng: 'withering rose', emoji: '🥀' },
  66: { name: '爱心', eng: 'heart', emoji: '❤' },
  67: { name: '心碎', eng: 'broken heart', emoji: '💔' },

  69: { name: '礼物', eng: 'gift', emoji: '🎁' },

  74: { name: '太阳', eng: 'sun', emoji: '🌞' },
  75: { name: '月亮', eng: 'moon', emoji: '🌙' },
  76: { name: '赞', eng: 'thumbs up', emoji: '👍' },
  77: { name: '踩', eng: 'thumbs down', emoji: '👎' },
  78: { name: '握手', eng: 'handshake', emoji: '🤝' },
  79: { name: '胜利', eng: 'peace sign', emoji: '✌' },

  85: { name: '飞吻', eng: 'blowing kisses', emoji: '😘' },
  86: { name: '怄火', eng: 'venting', emoji: '😠' },

  89: { name: '西瓜', eng: 'watermelon', emoji: '🍉' },

  96: { name: '冷汗', eng: 'nervous sweat', emoji: '😰' },
  97: { name: '擦汗', eng: 'wiping sweat' },
  98: { name: '抠鼻', eng: 'nose picking' },
  99: { name: '鼓掌', eng: 'applaud', emoji: '👏' },
  100: { name: '糗大了', eng: 'in shame', emoji: '😑' },
  101: { name: '坏笑', eng: 'smirking' },
  102: { name: '左哼哼', eng: 'humph to the left', emoji: '😤' },
  103: { name: '右哼哼', eng: 'humph to the right', emoji: '😤' },
  104: { name: '哈欠', eng: 'yawning', emoji: '🥱' },
  105: { name: '鄙视', eng: 'despise' },
  106: { name: '委屈', eng: 'shy and hesitate', emoji: '🙁' },
  107: { name: '快哭了', eng: 'sobbing', emoji: '😥' },
  108: { name: '阴险', eng: 'sinister', emoji: '😏' },
  109: { name: '左亲亲', eng: 'kissy to the left', emoji: '😚' },
  110: { name: '吓', eng: 'skrik', emoji: '😱' },
  111: { name: '可怜', eng: 'sparkly eyes', emoji: '🥺' },
  112: { name: '菜刀', eng: 'butcher knife', emoji: '🔪' },
  113: { name: '啤酒', eng: 'beer', emoji: '🍺' },
  114: { name: '篮球', eng: 'basketball', emoji: '🏀' },
  115: { name: '乒乓', eng: 'ping-pong', emoji: '🏓' },
  116: { name: '示爱', eng: 'kiss', emoji: '👄' },
  117: { name: '瓢虫', eng: 'ladybug', emoji: '🐞' },
  118: { name: '抱拳', eng: 'fist-palm salute', emoji: '🙏' },
  119: { name: '勾引', eng: 'beckoning finger' },
  120: { name: '拳头', eng: 'fist', emoji: '✊' },
  121: { name: '差劲', eng: 'pinky finger' },
  122: { name: '爱你', eng: 'rock hand', emoji: '🤟' },
  123: { name: 'NO', eng: 'wagging finger' },
  124: { name: 'OK', eng: 'ok sign', emoji: '👌' },
  125: { name: '转圈', eng: 'dance in circle' },
  126: { name: '磕头', eng: 'kowtow', emoji: '🙇' },
  127: { name: '回头', eng: 'looking back' },
  128: { name: '跳绳', eng: 'jump rope' },
  129: { name: '挥手', eng: 'waving', emoji: '👋' },
  130: { name: '激动', eng: 'excited' },
  131: { name: '街舞', eng: 'breakdance', emoji: '💃' },
  132: { name: '献吻', eng: 'give you a kiss', emoji: '😗' },
  133: { name: '左太极', eng: 'tai-chi to the left' },
  134: { name: '右太极', eng: 'tai-chi to the right' },

  136: { name: '双喜', eng: 'double happiness', emoji: '🉤' },
  137: { name: '鞭炮', eng: 'firecracker', emoji: '🧨' },
  138: { name: '灯笼', eng: 'chinese lantern', emoji: '🏮' },

  140: { name: 'K歌', eng: 'karaoke', emoji: '🎤' },

  144: { name: '喝彩', eng: 'party popper', emoji: '🎉' },
  145: { name: '祈祷', eng: 'candle', emoji: '🕯' },
  146: { name: '爆筋', eng: 'anger symbol', emoji: '💢' },
  147: { name: '棒棒糖', eng: 'lolipop', emoji: '🍭' },
  148: { name: '喝奶', eng: 'bady bottle', emoji: '🍼' },

  151: { name: '飞机', eng: 'plane', emoji: '✈' },

  158: { name: '钞票', eng: 'money', emoji: '💵' },

  168: { name: '药', eng: 'pill', emoji: '💊' },
  169: { name: '手枪', eng: 'gun', emoji: '🔫' },

  171: { name: '茶', eng: 'tee', emoji: '🍵' },
  172: { name: '眨眼睛', eng: 'winking', emoji: '😉' },
  173: { name: '泪奔', eng: 'runing and crying' },
  174: { name: '无奈', eng: 'shurg', emoji: '🤷' },
  175: { name: '卖萌', eng: 'acting cute' },
  176: { name: '小纠结', eng: 'cute thinking', emoji: '🤔' },
  177: { name: '喷血', eng: 'pfft' },
  178: { name: '斜眼笑', eng: 'trollface', emoji: '😏' },
  179: { name: 'doge', eng: 'doge face' },
  180: { name: '惊喜', eng: 'pleasantly surprised', emoji: '🤩' },
  181: { name: '骚扰', eng: 'pokey poke' },
  182: { name: '笑哭', eng: 'laughing tears', emoji: '😂' },
  183: { name: '我最美', eng: "i'm so pretty", emoji: '🥰' },
  184: { name: '河蟹', eng: 'crab', emoji: '🦀' },
  185: { name: '羊驼', eng: 'alpaca', emoji: '🦙' },

  187: { name: '幽灵', eng: 'ghost', emoji: '👻' },
  188: { name: '蛋', eng: 'egg', emoji: '🥚' },

  190: { name: '菊花', eng: 'chrysanthemum', emoji: '🌼' },

  192: { name: '红包', eng: 'red envelope', emoji: '🧧' },
  193: { name: '大笑', eng: 'laughing out loud', emoji: '😄' },
  194: { name: '不开心', eng: 'unhappy about it', emoji: '☹' },

  197: { name: '冷漠', eng: 'indifferent', emoji: '😐' },
  198: { name: '呃', eng: 'facepalm' },
  199: { name: '好棒', eng: 'hooray' },
  200: { name: '拜托', eng: 'please' },
  201: { name: '点赞', eng: 'thumbs up for you' },
  202: { name: '无聊', eng: 'bored' },
  203: { name: '托脸', eng: 'face rubing' },
  204: { name: '吃', eng: 'chewing' },
  205: { name: '送花', eng: 'rose for you', emoji: '💐' },
  206: { name: '害怕', eng: 'scary' },
  207: { name: '花痴', eng: 'in love' },
  208: { name: '小样儿', eng: 'chicken attack' },

  210: { name: '飙泪', eng: 'crying out loud' },
  211: { name: '我不看', eng: 'no looking', emoji: '🙈' },
  212: { name: '托腮', eng: 'hands under chin thinking' },
  214: { name: '啵啵', eng: 'kissy kiss' },
  215: { name: '糊脸', eng: 'throw it in your face' },
  216: { name: '拍头', eng: 'head smacking' },
  217: { name: '扯一扯', eng: 'face rubbing' },
  218: { name: '舔一舔', eng: 'licking' },
  219: { name: '蹭一蹭', eng: 'rubbing' },
  220: { name: '拽炸天', eng: 'peace and deal with it' },
  221: { name: '顶呱呱', eng: 'thumbs up combo' },
  222: { name: '抱抱', eng: 'give you a hug' },
  223: { name: '暴击', eng: 'critical damage' },
  224: { name: '开枪', eng: 'trigger happy' },
  225: { name: '撩一撩', eng: 'tickle' },
  226: { name: '拍桌', eng: 'slams table' },
  227: { name: '拍手', eng: 'clap clap' },
  228: { name: '恭喜', eng: 'congratulation' },
  229: { name: '干杯', eng: 'cheers' },
  230: { name: '嘲讽', eng: 'taunt' },
  231: { name: '哼', eng: 'humph' },
  232: { name: '佛系', eng: 'praying' },
  233: { name: '掐一掐', eng: 'chokehold' },
  235: { name: '颤抖', eng: 'trembling' },
  234: { name: '惊呆', eng: 'stunned' },
  236: { name: '啃头', eng: 'bit a piece of me' },

  237: { name: '偷看', eng: 'peeping' },
  238: { name: '扇脸', eng: 'face slapping' },
  239: { name: '原谅', eng: 'green hat' },
  240: { name: '喷脸', eng: 'spitting melon seeds' },
  241: { name: '生日快乐', eng: 'happy birthday' },
  242: { name: '头撞击', eng: 'head-butt' },
  243: { name: '甩头', eng: 'hair flicking' },
  244: { name: '扔狗', eng: 'throwing a dog' },
  245: { name: '加油必胜', eng: 'come on you can do it' },
  246: { name: '加油抱抱', eng: "i'll give you a hug" },
  247: { name: '口罩护体', eng: 'properly face masked', emoji: '😷' },

  260: { name: '搬砖中', eng: 'working' },
  261: { name: '忙到飞起', eng: 'busy as hell', emoji: '👨‍💻' },
  262: { name: '脑壳疼', eng: 'headache' },
  263: { name: '沧桑', eng: 'vicissitudes' },
  264: { name: '捂脸', eng: 'faceplam', emoji: '🤦' },
  265: { name: '辣眼睛', eng: "can't look" },
  266: { name: '哦哟', eng: 'huh' },
  267: { name: '头秃', eng: 'balding', emoji: '👨‍🦲' },
  268: { name: '问号脸', eng: '???' },
  269: { name: '暗中观察', eng: 'watching in the dark', emoji: '👀' },
  270: { name: 'emm', eng: 'emm' },
  271: { name: '吃瓜', eng: 'watermelon eater' },
  272: { name: '呵呵哒', eng: 'upside down smile', emoji: '🙃' },
  273: { name: '我酸了', eng: 'lemon', emoji: '🍋' },
  274: { name: '太南了', eng: 'gone south', emoji: '🀁' },

  277: { name: '汪汪', eng: 'doge' },
  278: { name: '汗', eng: 'looking around sweating' },
  279: { name: '打脸', eng: 'face punching' },
  280: { name: '击掌', eng: 'high five' },
  281: { name: '无眼笑', eng: 'rolling eyes and smiling' },
  282: { name: '敬礼', eng: 'salute' },
  283: { name: '狂笑', eng: 'laughing uncontrollably' },
  284: { name: '面无表情', eng: 'poker face' },
  285: { name: '摸鱼', eng: 'petting fish' },
  286: { name: '魔鬼笑', eng: 'reaper grinning' },
  287: { name: '哦', eng: 'sip' },
  288: { name: '请', eng: "there's the door" },
  289: { name: '睁眼', eng: 'open my eyes' },
  290: { name: '敲开心', eng: 'happiest man' },
  291: { name: '震惊', eng: 'shocking' },
  292: { name: '让我康康', eng: 'let me see' },
  293: { name: '摸锦鲤', eng: 'petting koi' },
  294: { name: '期待', eng: 'look forward to' },

  297: { name: '拜谢', eng: 'appreciate' },
  298: { name: '元宝', eng: 'dumpling ingot' },
  299: { name: '牛啊', eng: "you're amazing" },
  300: { name: '胖三斤', eng: 'put on some weight' },
  301: { name: '好闪', eng: 'like a flashbang' },
  305: { name: '右亲亲', eng: 'kissy to the right', emoji: '😚' },
  306: { name: '牛气冲天', eng: "you're outta this world" },
  307: { name: '喵喵', eng: 'kitty' },
  308: { name: '求红包', eng: 'beg for cash' },
  309: { name: '谢红包', eng: 'thanks for the money' },
  310: { name: '新年烟花', eng: 'firework' },
  311: { name: '打call', eng: 'glow sticks' },
  312: { name: '变形', eng: "i'm torn" },

  314: { name: '仔细分析', eng: 'analyzing' },
  315: { name: '加油', eng: 'flexing' },

  317: { name: '菜汪', eng: 'cabbage doge' },
  318: { name: '崇拜', eng: 'blushing' },
  319: { name: '比心', eng: 'heart gesture' },
  320: { name: '庆祝', eng: 'celebration' },
  322: { name: '拒绝', eng: 'i refuse' },
  323: { name: '嫌弃', eng: 'disgusted' },
  324: { name: '吃糖', eng: 'lolipop demolisher' },
  325: { name: '惊吓', eng: 'der schrei' },
  326: { name: '生气', eng: 'robo rage' },
};
