name: Deploy

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:
      - uses: actions/checkout@master

      - name: Bucket actions
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run build

      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: ./*
          host: ${{ secrets.SSH_HOST }}
          remote: ${{ secrets.SSH_DIR }}
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}

      - name: Post command
        uses: appleboy/ssh-action@master
        env:
          WORKING_DIR: ${{ secrets.SSH_DIR }}
          DEPLOY_COMMANDS: ${{ secrets.DEPLOY_COMMANDS }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd $WORKING_DIR
            bash -c $DEPLOY_COMMANDS
